### ISSUE TITLE
dd failed with exit status "1"

### ISSUE THREAD

**Issue by monkeydri** [slacka/WoeUSB#164]
Trying to burn Win 10 on USB key with sufficient space and not mounted.
ISO file downloaded from Microsoft website, SHA1sum correct. version is en_windows_10_multi-edition_vl_version_1709_updated_dec_2017_x64_dvd_100406172.iso

Process goes smoothly almost till the end and then error below appears :

```
Installation failed!
Exit code: 256
Log:
/usr/bin/woeusb: line 433: local: warning: only_for_gui_ref: circular name reference
/usr/bin/woeusb: line 433: warning: only_for_gui_ref: circular name reference
/usr/bin/woeusb: line 508: warning: only_for_gui_ref: circular name reference
WoeUSB v3.1.4-14-g626b1bf
==============================
Wiping all existing partition table and filesystem signatures in /dev/sdc...
/dev/sdc: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sdc: calling ioctl to re-read partition table: Success
Ensure that /dev/sdc is really wiped...
Creating new partition table on /dev/sdc...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkfs.fat 4.1 (2017-01-24)
Mounting source filesystem...
Mounting target filesystem...
Applying workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
Copying files from source media...
The command "dd if="${source_file}" bs="${DD_BLOCK_SIZE}" skip="${i}" seek="${i}" of="${dest_file}" count=1 2> /dev/null" failed with exit status "1", program is prematurely aborted
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
/usr/bin/woeusb: line 1608: local: only_for_gui: readonly variable
Unmounting and removing '/media/woeusb_source_1520937105_13470'...
Unmounting and removing '/media/woeusb_target_1520937105_13470'...
You may now safely detach the target device
```

- WoeUSB v3.1.4-14-g626b1bf compiled from source (626b1bf4f24d4b69f1b87f775bc6c803535cf8d9) following README.md instructions. Also happens on WebUpd8 PPA 3.1.4-1~webupd8~artful0 (WoeUSB from this PPA showed incorrect version :  ` @@WOEUSB_VERSION@@`)
- Ubuntu 17.10 on wayland
- GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
- SD card : Kingston 32GB

I still tried to install Win10 from this USB key as I read that WoeUSB errors can sometimes be ignored. It booted but failed at the step searching for HDD drivers.

**Comment by Lin-Buo-Ren** [comment]
Hello, please try using the command-line version `woeusb` instead and see if your issue can be reproduced, refer the manpage if you need any help.

**Comment by eutektoid** [comment]
Hello @monkeydri, hello @Lin-Buo-Ren , 
I encountered the problem as well (Exit Code: 256). In my opinion the problem is somehow related to the formatting of the stick. 
So like some people I tried to unmount, format to NTFS before, etc. with GParted --- if failed too.
After that I tried to use the CLI.
First I typed
`woeusb --help`

and read through the options.
I found the interesting line:
`--target-filesystem, --tgt-fs <filesystem name>`
`Specify the filesystem to use as the target partition's filesystem.`
`Currently supported: FAT(default)/NTFS`

So after I typed:
`sudo woeusb --device image.iso /dev/sdb --tgt-fs NTFS --verbose`

This took a very long time compared to the process via GUI, but in the end it read:

`Done :)`
`The target device should be bootable now`

(I'm not sure anymore, if I unmounted the stick prior to that CLI process.)

So I would say, although I formatted the stick before to NTFS, using the GUI version formatted the stick with FAT. 
I also assume, that the install fails, because some files in the Windows 10 image are larger than 4GB. 
When I used the CLI it worked because I specifically choose the format option `--tgt-fs NTFS ` (at least that is what I assume).

There is just the fact that apparently some users don't encounter this problem using the GUI, which is odd. 

I used:
- Linux Mint 18.3
-  `ppa:nilarimogard/webupd8`

@monkeydri I also tried to install Windows 10 with that error and encountered the 'searching for drivers'-issue!

**Comment by monkeydri** [comment]
Hi @eutektoid, thanks for your help ! Pre-format the SD card does not help, because WoeUSB re-formats in anyway at the beginning. It does so without problem, the  error occurs later at the copying phase. *As a matter of fact I did format the card (FAT32) before using WoeUSB (having in mind Unetbootin which made non bootable stick if not properly formatted before)*. Also, I tried WoeUSB again after SD card was formatted with Rufus (which led to a successful Win10 install) so with proper formatting.

@Lin-Buo-Ren `sudo woeusb --device en_windows_10_multi-edition_vl_version_1709_updated_dec_2017_x64_dvd_100406172.iso /dev/sdc --verbose` failed at the copying phase at 9% (on the GUI progress bar was more like 90%) with error `The command "dd if="${source_file}" bs="${DD_BLOCK_SIZE}" skip="${i}" seek="${i}" of="${dest_file}" count=1 2> /dev/null" failed with exit status "1", program is prematurely aborted`. The culprit file seems to be `./sources/install.wim`.

But `--tgt-fs NTFS` option did the trick ! (I did not try the install though as I already installed WIN10 in the meantime).

So the problem is that FAT32 is used for formatting instead NTFS, I suppose some windows files on the ISO cannot be copied to FAT filesystem because something like permissions cannot be transfered.

=> There should be an option for NTFS in the GUI also. Or better a section for formatting (in between the ISO file and target device sections) where we could choose between MBR/GPT partition table and select filesystem, just like Rufus.

*Note : the CLI is indeed much slower than the GUI for copying files !*

**Comment by Lin-Buo-Ren** [comment]
> The culprit file seems to be ./sources/install.wim.
You've encountered the [FAT32 Filesystem 4GiB Single File Size Limitation](https://github.com/slacka/WoeUSB/wiki/Limitations#fat32-filesystem-4gib-single-file-size-limitation).

> There should be an option for NTFS in the GUI also (etc)
I agree, but unfortunately no one is into the task for now.

**Comment by dkleined** [comment]
I am experiencing this same problem in Fedora, and using the NTFS flag does not resolve it.

**Comment by RafaelLinux** [comment]
WoeUSB v3.2.1, USB 8GiB exFAT formatted.
I'm using exFAT format, that have no the FAT32 limitations. However, this problems is present (2019). I do not consider this issue closed.

**Comment by JonnyTech** [comment]
AFAIK exFAT does not support bootable install mediums, please use NTFS

**Comment by RafaelLinux** [comment]
You have reason. I presumed exFAT (as a FAT extension) was EFI bootable, but as you said, EFI specification only consider FAT12-16-32. Anyway, I try NTFS.
Thank you

**Comment by DevHerrera** [comment]
I still have the probem, Fedora 32.

**Comment by ahjun001** [comment]
Same problem on Linux Mint 20 / Cinnamon
GUI: NTFS
CLI:  sudo woeusb --device image.iso /dev/sdb --tgt-fs NTFS --verbose

Both aborted with error message:  "The command "dd if="${source_file}" bs="${DD_BLOCK_SIZE}" skip="${i}" seek="${i}" of="${dest_file}" count=1 2> /dev/null" failed with exit status "1", program is prematurely aborted"

Got woeusb app from : https://github.com/slacka/WoeUSB/files/4622440/woeusb.zip  : all other options (ppa, deb, installing uninstallable dependencies ... ) would not work.

**Comment by JonnyTech** [comment]
Make sure that partitions on target usb drive and source iso file are not mounted.

**Comment by ahjun001** [comment]
Yes, thank you @JonnyTech

MY BAD: I later used Rufus on a Windows machine and found that the two ISOs I had tried with woeusb both had problems, wrongly leading me to think woeusb was the problem.
When selecting the iso file, Rufus warned about « Truncated ISO detected » : The ISO file you have selected does not match its declared size : 1.5 GB of data is missing !

And of course back in linux, $ sham1sum image.iso did not match the expected SHA1.

Using a new image.iso, having checked SHA1 this time, the CLI version aborted prematurely again, with messages as follows:

The command "dd if="${source_file}" bs="${DD_BLOCK_SIZE}" skip="${i}" seek="${i}" of="${dest_file}" count=1 2> /dev/null" failed with exit status "1", program is prematurely aborted

/usr/bin/woeusb: line 1789: local: only_for_gui: readonly variable



But then, WOEUSB GUI VERSION DID WORKED on LinuxMint 20 / Cinnamon, producing a usb I could then boot from.

So ... apologies for not having checked the integrity of my image.iso s before reporting to the group … Thank you all for the good work !
