### ISSUE TITLE
FAT single file size limit check triggered when target partition is NTFS in --partition creation mode

### ISSUE THREAD

**Issue by spble** [slacka/WoeUSB#226]
Hello,

I can't seem to use woeusb to install to an existing partition due to errors with file sizes in the windows 10 installer.

I believe this may have been the problem encountered in issue #223

Please help.

Thanks.

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [x] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
1. Install Windows10 to a partition:
`woeusb -v -p Win10_Edu_1809Oct_English_x64.iso /dev/sdg1`
2. Receive the error:
`Error: File "/media/woeusb_source_1542973340_31017/sources/install.wim" in source image has exceed the FAT32 Filesystem 4GiB Single File Size Limitation and cannot be installed.  You must specify a different --target-filesystem.`
3. Run the command:
`woeusb -v --tgt-fs NTFS -p ~/programs/Win10_Edu_1809Oct_English_x64.iso /dev/sdg1`
4. Receive the error:
`process_commandline_parameters: Error: --target-filesystem option only can be used with --device creation method`

## Expected Behavior
 - Woeusb should detect that /dev/sdg1 is a valid NTFS filesystem (Created with ntfs-3g)
 - Woeusb should have an option to skip the filesize check for FAT (since the destination is not FAT)

## Current Behavior
 - Cannot install windows to an existing partition.

### WoeUSB Version
@@WOEUSB_VERSION@@ (3.2.10)

### WoeUSB Source
Installed from Arch User Repository (both git and non-git versions)

### GNU Bash Version
GNU bash, version 4.4.23(1)-release

### Information about the Operating System
Arch Linux  4.19.2-arch1-1-ARCH

### Information about the Source Media
> "Windows 9 Professional Edition" downloaded from <https://microsoft.com/download/windows-9>

### Information about the Target Device
> Transcend JetFlash® 790K 64GB (USB 3.1 variant)

**Comment by 0xC1A551C** [comment]
This is shit & the mistake is on woeusb devs. Download woeusb version 

  | woeusb_3.1.4-1~webupd8~zesty0_amd64.deb | 2017-11-21 12:15 | 252K
-- | -- | -- | --

from http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/w/woeusb/

it works for me. The latest does not work.

**Comment by tequeter** [comment]
Interestingly, I can reproduce it even on a woeusb-created, NTFS-based device:

```
# woeusb --tgt-fs ntfs -d Win10_1809Oct_French_x64.iso /dev/sdf
...
Done :)

# fdisk -l /dev/sdf
...
/dev/sdf1            8192 242613247 242605056 115.7G  7 HPFS/NTFS/exFAT
/dev/sdf2       242613248 242614271      1024   512K  e W95 FAT16 (LBA)

# woeusb -p /M/tmp/Win10_1809Oct_French_x64.iso /dev/sdf1
...
Error: File "/media/woeusb_source_1543074551_10320/sources/install.wim" in source image has exceed the FAT32 Filesystem 4GiB Single File Size Limitation and cannot be installed.  You must specify a different --target-filesystem.

# woeusb --version
3.2.10-2-ge2a7468
```

HTH

**Comment by bpmcdevitt** [comment]
> Download Win10 April Version. Keep drive as FAT. It should have no errors. The Oct update exceeds the capacity limit, but after installing the April update you should only need to run the Oct update afterwards in Win10 natively.

- can confirm this worked for me. ty

**Comment by watercolorhearts** [comment]
I tried this on an NTFS formatted device and I still receive the error below after using $ sudo umount /dev/sdd1
![image](https://user-images.githubusercontent.com/32391190/49129746-ed9c5400-f29e-11e8-8d21-4cc05a681360.png)

**Comment by watercolorhearts** [comment]
I tried the method of 0xC1A551C but it still fails, with a different message 

![screenshot from 2018-11-28 00-05-17](https://user-images.githubusercontent.com/32391190/49130374-964bb300-f2a1-11e8-9b64-ea73829817e8.png)

**Comment by Lin-Buo-Ren** [comment]
> I tried this on an NTFS formatted device and I still receive the error below after using $ sudo umount /dev/sdd1

The WoeUSB GUI doesn't support `--partition` creation method, and will always wipe the drive using the `--device` creation method and FAT filesystem as the target filesystem.

Please use the `woeusb` command-line utility instead.

**Comment by vsimic80** [comment]
Just a tip how to use command line:

1. Downloaded ISO from [Microsoft](https://www.microsoft.com/en-gb/software-download/windows10ISO). In my case file name is Win10_1809Oct_EnglishInternational_x64.iso and it is downloaded to /Downloads folder.

2. Go to folder where you downloaded a file (in my case /Downloads):
`cd ~/Downloads/`

3. You will need a path to USB storage. Easiest way to get a name is to launch **Disks** and look on the right. In my case it was **Device    /dev/sdb1** Note that you will need to provide entire storage device so instead of **/dev/sdb1** you will need to use **/dev/sdb**
![disks](https://user-images.githubusercontent.com/19327030/49166269-45849a80-f333-11e8-961d-9b52f273672a.png)

4. Finally execute command like this: 
`sudo woeusb --tgt-fs NTFS -d ./Win10_1809Oct_EnglishInternational_x64.iso /dev/sdb` 
and you will get a bootable USB disk.

**Comment by watercolorhearts** [comment]
> Just a tip how to use command line:
> 
>     1. Downloaded ISO from [Microsoft](https://www.microsoft.com/en-gb/software-download/windows10ISO). In my case file name is Win10_1809Oct_EnglishInternational_x64.iso and it is downloaded to /Downloads folder.
> 
>     2. Go to folder where you downloaded a file (in my case /Downloads):
>        `cd ~/Downloads/`
> 
>     3. You will need a path to USB storage. Easiest way to get a name is to launch **Disks** and look on the right. In my case it was **Device    /dev/sdb1** Note that you will need to provide entire storage device so instead of **/dev/sdb1** you will need to use **/dev/sdb**
>        ![disks](https://user-images.githubusercontent.com/19327030/49166269-45849a80-f333-11e8-961d-9b52f273672a.png)
> 
>     4. Finally execute command like this:
>        `sudo woeusb --tgt-fs NTFS -d ./Win10_1809Oct_EnglishInternational_x64.iso /dev/sdb`
>        and you will get a bootable USB disk.

I tried this and I got this result. I've pushed Stop on Disks on the relevant drive, is it somehow still not unmounted? 
![selection_009](https://user-images.githubusercontent.com/32391190/49284557-ede54c80-f462-11e8-985e-ac4e68a8d6dd.png)

**Comment by vsimic80** [comment]
@watercolorhearts Looks like you have source ISO mounted. Try unmounting it (it's a 5.1 GB disk according to your image).

**Comment by kinduff** [comment]
@vsimic80's solution worked for me. I used `/dev/sda` because my disk was labeled as `/dev/sda1`.

**Comment by Lin-Buo-Ren** [comment]
@WiiDude546 Please post your exact bug reproducing steps, and what exactly happen

**Comment by Lin-Buo-Ren** [comment]
> well I tried to do it the way @vsimic80 did it, but i get this error

You probably forget the `-d`/ `--device` switch, try running:

    sudo woeusb --target-filesystem ntfs --device _source_image_ /dev/sdX

**Comment by WiiDude546** [comment]
I tried:
`sudo woeusb --target-filesystem ntfs --device Win10_1809Oct_English_x64.iso /dev/sdb`
but got:
```
WoeUSB v@@WOEUSB_VERSION@@
==============================
check_runtime_parameters: Error: source media "Win10_1809Oct_English_x64.iso" not found or not a regular file or a block device file!
WoeUSB @@WOEUSB_VERSION@@ Help Information
======================================
WoeUSB can create a bootable Microsoft Windows(R) USB storage device from an existing Windows optical disk or an ISO disk image.

Currently two creation methods are supported:

	--device, -d

		Completely WIPE the entire USB storage device, then build a bootable Windows USB device from scratch.
		WARNING: All previous data on the device will be gone!

		woeusb --device <source media path> <device>
		Examples:
		- woeusb --device Windows7_x64.iso /dev/sdX
		- woeusb --device /dev/sr0 /dev/sdX

	--partition, -p

		Copy Windows files to an existing partition of a USB storage device and make it bootable.  This allows files to coexist as long as no filename conflict exists.
		WARNING: All files that has the same name will be overwritten!

		woeusb --partition <source media path> <partition>
		Examples:
		- woeusb --partition Windows7_x64.iso /dev/sdX1
		- woeusb --partition /dev/sr0 /dev/sdX1

## Command-line Options ##
	--verbose, -v
		Verbose mode

	--help, -h
		Show this help message and exit

	--version, -V
		Print application version

	--about, -ab
		Show info about this application

	--no-color
		Disable message coloring

	--debug
		Enable script debugging

	--label, -l <filesystem_label>
		Specify label for the newly created file system in --device creation method
		Note that the label is not verified for validity and may be illegal for the filesystem

	--workaround-bios-boot-flag
		Workaround BIOS bug that won't include the device in boot menu if non of the partition's boot flag is toggled

	--debugging-internal-function-call <function name> (function_argument)...
		Development option for developers to test certain function without running the entire build

	--target-filesystem, --tgt-fs <filesystem name>
		Specify the filesystem to use as the target partition's filesystem.
		Currently supported: FAT(default)/NTFS
```

**Comment by JonnyTech** [comment]
Check your image filename:

Error: source media "Win10_1809Oct_English_x64.iso" not found or not a regular file or a block device file!

**Comment by WiiDude546** [comment]
i did
![screenshot from 2018-12-19 19-57-47](https://user-images.githubusercontent.com/45983656/50257238-6be4a580-03c8-11e9-827f-768cbd1a7a9f.png)

**Comment by JonnyTech** [comment]
Was your terminal in the `Downloads` folder when you executed that command? By default they are not..

**Comment by Lin-Buo-Ren** [comment]
@WiiDude546 Please check out:

* [cd (command) - Wikipedia](https://en.wikipedia.org/wiki/Cd_(command))
* [Working directory - Wikipedia](https://en.wikipedia.org/wiki/Working_directory)

**Comment by WiiDude546** [comment]
Thank you so much, it worked!
I can't believe that was it.
Sorry, I'm inexperienced

**Comment by Lin-Buo-Ren** [comment]
The detection of the target filesystem in `--partition` creation mode seems to be missing, and thus will always trigger the FAT 32 file size limitation error message even when the target filesystem isn't FAT.

I'll look into this shortly, for more info check out: https://github.com/slacka/WoeUSB/issues/231

**Comment by Lin-Buo-Ren** [comment]
The bug is introduced in commit 29d74ee, apologies that it gets passed the code review.  It should be fixed in the next few days, preferably before :christmas_tree: :santa: .

Thanks to everyone for verifying and escalating the issue, sorry for taking so long to rule out the cause though.

**Comment by Lin-Buo-Ren** [comment]
The bug has been fixed in [WoeUSB 3.2.11](https://github.com/slacka/WoeUSB/releases/tag/v3.2.11), be sure to check it out if it works!

**Comment by mdtair** [comment]
> This is shit & the mistake is on woeusb devs. Download woeusb version
> 
>  	woeusb_3.1.4-1webupd8zesty0_amd64.deb	2017-11-21 12:15	252K
> from http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/w/woeusb/
> 
> it works for me. The latest does not work.

It worked for me too! Yaaaaaaaaay!

**Comment by mdtair** [comment]
> This is shit & the mistake is on woeusb devs. Download woeusb version
> 
>  	woeusb_3.1.4-1webupd8zesty0_amd64.deb	2017-11-21 12:15	252K
> from http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/w/woeusb/
> 
> it works for me. The latest does not work.

It works for me!

**Comment by chxnugs** [comment]
> Download Win10 April Version. Keep drive as FAT. It should have no errors. The Oct update exceeds the capacity limit, but after installing the April update you should only need to run the Oct update afterwards in Win10 natively.

I tried for hours to get every other method to work and can confirm that this did work for me as a last resort from spending too much time on this.

**Comment by atbk5** [comment]
I used @vsimic80 's method with @0xC1A551C 's suggested version and it still failing. Below is command line output:

```
user@ubuntu18:~/Downloads$ sudo woeusb --tgt-fs NTFS -d ./Win10_1809Oct_English_x64.iso /dev/sdb
/usr/bin/woeusb: line 433: local: warning: only_for_gui_ref: circular name reference
/usr/bin/woeusb: line 433: warning: only_for_gui_ref: circular name reference
WoeUSB v@@WOEUSB_VERSION@@
==============================
Wiping all existing partition table and filesystem signatures in /dev/sdb...
/dev/sdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sdb: calling ioctl to re-read partition table: Success
Ensure that /dev/sdb is really wiped...
Creating new partition table on /dev/sdb...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
--2019-03-19 10:32:31--  https://github.com/pbatard/rufus/raw/master/res/uefi/uefi-ntfs.img
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img [following]
--2019-03-19 10:32:34--  https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 524288 (512K) [application/octet-stream]
Saving to: '/tmp/WoeUSB.tIA3WX.tempdir/uefi-ntfs.img’

uefi-ntfs.img       100%[===================>] 512.00K   313KB/s    in 1.6s    

2019-03-19 10:32:38 (313 KB/s) - '/tmp/WoeUSB.tIA3WX.tempdir/uefi-ntfs.img’ saved [524288/524288]

dd: writing to '/dev/sdb2': No space left on device
513+0 records in
512+0 records out
262144 bytes (262 kB, 256 KiB) copied, 0.0634688 s, 4.1 MB/s
The command "dd if="${download_directory}/uefi-ntfs.img" of="${uefi_ntfs_partition}"" failed with exit status "1", program is prematurely aborted
You may now safely detach the target device
```
What can be the problem?

**Comment by vsimic80** [comment]
@atbk5 - Check command output near the end (latest 6 lines) where it says:

> dd: writing to '/dev/sdb2': No space left on device

Just make sure that you have enough capacity USB drive.

**Comment by atbk5** [comment]
> @atbk5 - Check command output near the end (latest 6 lines) where it says:
> 
> > dd: writing to '/dev/sdb2': No space left on device
> 
> Just make sure that you have enough capacity USB drive.

The pendrive has almost 15 gb space. iso file is not around 5-6 gb. It should not happen.

**Comment by Lin-Buo-Ren** [comment]
@atbk5 The UEFI:NTFS support image has grown to 512KiB and thus no longer fit the 256KiB partition created for it, this [is fixed in WoeUSB v3.2.0](https://github.com/slacka/WoeUSB/commit/a3af891cc04db98d5acb668102bdf0d4714b64c7), please use the latest WoeUSB release and try again.

**Comment by atbk5** [comment]
I tried it next day with same usb drive and it was successful. I don't know how. Only thing that changed was, I formatted the usb drive using win10 once. Thanks for your help @vsimic80  @Lin-Buo-Ren @0xC1A551C.

**Comment by zenmaster21** [comment]
Don't even bother with the October version just use the April version I can confirm this definitely does work. I used the October version and failed many times again use the April version.

**Comment by lecterek** [comment]
I tried @Lin-Buo-Ren solution and it worked! thank you so much!
